### ISSUE TITLE
Create a way to external reference query value pairs

### ISSUE THREAD

**Issue by p3nGu1nZz** [MultiTonic/thinking-dataset#47]
this will allow us to shorten up the contractions and terms config node in the NormalizeTextPipe.

maybe something as simple as: 
```yaml
    - pipe:
        type: "NormalizeTextPipe"
        config:
          columns: [ "cable" ]
          contractions:
            - file: "./assets/dict/contractions.txt"
          terms:
            - file: "./assets/dict/terms.txt"
```

**specification**
- the `config.py` will need to be updated to look for the file attribute first. 
- should be able to mix query value pairs and file. 
- should be able to have multiple files defined. eg. terms_a.txt + terms_b.txt
